import { fmtDateTime, peso } from '$lib/beezy/format';
import { calcActivity, type ActivityLike, type SettlementEvent } from '$lib/beezy/settlement';

/** Activity fields required to render a plain-text receipt summary. */
export interface ActivitySummaryInput extends ActivityLike {
	name: string;
	createdAt: string;
}

/** Event fields required for the summary header and split math. */
export interface ActivitySummaryEvent extends SettlementEvent {
	title: string;
}

/**
 * Plain-text receipt for copy-to-clipboard (no DOM or clipboard APIs).
 * Layout matches mockup `copyActivitySummary()`; branding uses Beezy.
 */
export function formatActivitySummary(
	activity: ActivitySummaryInput,
	event: ActivitySummaryEvent,
	_activities?: ActivityLike[]
): string {
	const ac = calcActivity(activity, event);
	const payerName = ac.payer ? ac.payer.name : '—';
	const lines: string[] = [];

	lines.push('🤗 Beezy — ' + event.title);
	lines.push(activity.name);
	lines.push(fmtDateTime(activity.createdAt));
	lines.push('----------------------------------');
	lines.push('Paid by:      ' + payerName);
	lines.push('Total:        ' + peso(ac.total));
	lines.push('Split between ' + ac.n + (ac.n === 1 ? ' person' : ' people'));
	lines.push('Each pays:    ' + (ac.n ? peso(ac.share) : '—'));

	if (ac.others.length) {
		lines.push('----------------------------------');
		lines.push(payerName + ' collects:');
		for (const p of ac.others) {
			lines.push('  ' + p.name.padEnd(10) + ' ' + peso(ac.share));
		}
		lines.push('  ' + 'TOTAL'.padEnd(10) + ' ' + peso(ac.others.length * ac.share));
	}

	lines.push('----------------------------------');
	lines.push(activity.settled ? '✔ Settled' : 'Tap Settle in Beezy when paid');
	lines.push('Generated by Beezy (offline)');

	return lines.join('\n');
}
